"""Second  Migration

Revision ID: 6debfebfbecc
Revises: a7a72b6f5e19
Create Date: 2024-04-03 14:27:19.104013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6debfebfbecc'
down_revision = 'a7a72b6f5e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('quanity')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('user_id_idx', ['user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quanity', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.create_index('catergory_id_idx', ['category_id'], unique=False)

    # ### end Alembic commands ###
