"""First Migration

Revision ID: a7a72b6f5e19
Revises: 
Create Date: 2024-04-03 13:16:08.725029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7a72b6f5e19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('product_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)


    with op.batch_alter_table('orders', schema=None) as batch_op:

        batch_op.alter_column('purchase_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))


    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('product_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('delivery_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('phonenumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)


    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('isAdmin',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index('iduser_UNIQUE')
        batch_op.drop_table_comment(
        existing_comment='\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
        existing_comment=None
    )
        batch_op.create_index('iduser_UNIQUE', ['id'], unique=True)
        batch_op.alter_column('isAdmin',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index('user_id_idx', ['user_id'], unique=False)
        batch_op.alter_column('phonenumber',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('delivery_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('product_code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('merchandise', schema=None) as batch_op:
        batch_op.create_index('category_id_idx', ['category_id'], unique=False)
        batch_op.alter_column('product_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
